use std::fs;
use std::path::Path;

use toml_edit::{Array, DocumentMut, InlineTable, Item, Value};

use crate::config::{AgentSource, BuildConfig};

/// Generate `src/agents.rs` with imports for each agent.
pub fn generate_agents_rs(config: &BuildConfig, cli_root: &Path) -> Result<(), String> {
    let agents_path = cli_root.join("src/agents.rs");

    let mut content = String::from(
        "//! Agent crate imports (auto-generated by ma-build, do not edit)\n\
         //!\n\
         //! Each `use` pulls in the crate, causing #[modular_agent] registrations\n\
         //! to be linked via the `inventory` crate.\n",
    );

    for agent in &config.agents {
        let crate_name = agent.rust_crate_name();
        content.push_str(&format!(
            "\n#[allow(unused_imports)]\n\
             use {crate_name};\n"
        ));
    }

    // Backup existing file
    backup_file(&agents_path)?;
    fs::write(&agents_path, content).map_err(|e| format!("Failed to write agents.rs: {e}"))
}

/// Update `Cargo.toml` with the selected agents as optional dependencies.
pub fn update_cargo_toml(config: &BuildConfig, cli_root: &Path) -> Result<(), String> {
    let cargo_path = cli_root.join("Cargo.toml");
    let original =
        fs::read_to_string(&cargo_path).map_err(|e| format!("Failed to read Cargo.toml: {e}"))?;

    // Backup
    backup_file(&cargo_path)?;

    let mut doc: DocumentMut = original
        .parse()
        .map_err(|e| format!("Failed to parse Cargo.toml: {e}"))?;

    // Update dependencies
    update_dependencies(&mut doc, config)?;

    // Remove [features] section (no longer needed; ma-build manages deps directly)
    doc.remove("features");

    // Remove [patch] section unconditionally (no longer needed)
    doc.remove("patch");

    fs::write(&cargo_path, doc.to_string()).map_err(|e| format!("Failed to write Cargo.toml: {e}"))
}

/// Ensure `src/main.rs` has `mod agents;` and remove old inline imports.
pub fn update_main_rs(cli_root: &Path) -> Result<(), String> {
    let main_path = cli_root.join("src/main.rs");
    let content =
        fs::read_to_string(&main_path).map_err(|e| format!("Failed to read main.rs: {e}"))?;

    // Check if `mod agents;` already exists
    if content.contains("mod agents;") {
        // Already has the module declaration; just remove old imports if present
        let cleaned = remove_old_imports(&content);
        if cleaned != content {
            backup_file(&main_path)?;
            fs::write(&main_path, cleaned).map_err(|e| format!("Failed to write main.rs: {e}"))?;
        }
        return Ok(());
    }

    backup_file(&main_path)?;

    // Remove old feature-gated imports and add `mod agents;`
    let cleaned = remove_old_imports(&content);

    // Insert `mod agents;` after the initial `use` block
    let new_content = insert_mod_agents(&cleaned);

    fs::write(&main_path, new_content).map_err(|e| format!("Failed to write main.rs: {e}"))
}

fn update_dependencies(doc: &mut DocumentMut, config: &BuildConfig) -> Result<(), String> {
    let deps = doc["dependencies"]
        .as_table_mut()
        .ok_or("Missing [dependencies] in Cargo.toml")?;

    // Remove all modular-agent-* deps (including core; all will be re-added)
    let keys_to_remove: Vec<String> = deps
        .iter()
        .filter_map(|(key, _)| {
            if key.starts_with("modular-agent-") {
                Some(key.to_string())
            } else {
                None
            }
        })
        .collect();

    for key in keys_to_remove {
        deps.remove(&key);
    }

    // Add core
    deps.insert(
        "modular-agent-core",
        Item::Value(source_to_toml_value(&config.core)),
    );

    // Add selected agents
    for agent in &config.agents {
        let mut dep = source_to_inline_table(&agent.source);
        if let Some(features) = &agent.crate_features {
            dep.insert("default-features", Value::from(false));
            let mut features_array = Array::new();
            for f in features {
                features_array.push(f.as_str());
            }
            dep.insert("features", Value::from(features_array));
        }

        deps.insert(&agent.name, Item::Value(Value::InlineTable(dep)));
    }

    Ok(())
}

fn source_to_inline_table(source: &AgentSource) -> InlineTable {
    let mut dep = InlineTable::new();
    match source {
        AgentSource::Path { path } => {
            dep.insert("path", Value::from(normalize_path(path)));
        }
        AgentSource::Git { url, tag } => {
            dep.insert("git", Value::from(url.as_str()));
            if let Some(tag) = tag {
                dep.insert("tag", Value::from(tag.as_str()));
            }
        }
        AgentSource::Registry { version } => {
            dep.insert("version", Value::from(version.as_str()));
        }
    }
    dep
}

fn source_to_toml_value(source: &AgentSource) -> Value {
    match source {
        AgentSource::Registry { version } => Value::from(version.as_str()),
        _ => Value::InlineTable(source_to_inline_table(source)),
    }
}

/// Remove old inline feature-gated agent imports from main.rs.
fn remove_old_imports(content: &str) -> String {
    let lines: Vec<&str> = content.lines().collect();
    let mut result = Vec::new();
    let mut i = 0;

    while i < lines.len() {
        // Detect pattern: #[cfg(feature = "...")] + #[allow(unused_imports)] + use modular_agent_*;
        if i + 2 < lines.len()
            && lines[i].trim().starts_with("#[cfg(feature = \"")
            && lines[i + 1].trim() == "#[allow(unused_imports)]"
            && lines[i + 2].trim().starts_with("use modular_agent_")
        {
            i += 3;
            // Skip trailing blank line
            if i < lines.len() && lines[i].trim().is_empty() {
                i += 1;
            }
            continue;
        }

        // Also skip the comment block about feature-gated imports
        if lines[i].trim() == "// Feature-gated imports to trigger inventory registration."
            || lines[i].trim()
                == "// Each `use` pulls in the crate, causing #[modular_agent] registrations to be linked."
        {
            i += 1;
            // Skip trailing blank line
            if i < lines.len() && lines[i].trim().is_empty() {
                i += 1;
            }
            continue;
        }

        result.push(lines[i]);
        i += 1;
    }

    result.join("\n") + "\n"
}

/// Insert `mod agents;` after the initial use-statement block.
fn insert_mod_agents(content: &str) -> String {
    let lines: Vec<&str> = content.lines().collect();
    let mut result = Vec::new();
    let mut inserted = false;

    for (i, line) in lines.iter().enumerate() {
        result.push(*line);

        // Insert after the last top-level `use` statement, before `#[derive(Parser)]`
        if !inserted && line.trim().starts_with("use ") {
            // Check if next non-empty line is NOT a use statement
            let next_non_empty = lines[i + 1..]
                .iter()
                .find(|l| !l.trim().is_empty())
                .unwrap_or(&"");
            if !next_non_empty.trim().starts_with("use ") {
                result.push("");
                result.push("mod agents;");
                inserted = true;
            }
        }
    }

    if !inserted {
        // Fallback: insert at the top after the first line
        result.insert(1, "mod agents;");
        result.insert(1, "");
    }

    result.join("\n") + "\n"
}

fn backup_file(path: &Path) -> Result<(), String> {
    if path.exists() {
        let backup = path.with_extension(format!(
            "{}.bak",
            path.extension().and_then(|e| e.to_str()).unwrap_or("bak")
        ));
        fs::copy(path, &backup).map_err(|e| format!("Failed to backup {}: {e}", path.display()))?;
    }
    Ok(())
}

pub fn restore_backups(cli_root: &Path) {
    let files = [("Cargo.toml", "toml.bak"), ("src/agents.rs", "rs.bak")];

    for (original, backup_ext) in &files {
        let original_path = cli_root.join(original);
        let backup_path = original_path.with_extension(backup_ext);
        if backup_path.exists() {
            if let Err(e) = fs::copy(&backup_path, &original_path) {
                eprintln!("Failed to restore {original}: {e}");
            } else {
                let _ = fs::remove_file(&backup_path);
                eprintln!("Restored {original} from backup");
            }
        }
    }
}

pub fn cleanup_backups(cli_root: &Path) {
    let files = ["Cargo.toml.toml.bak", "src/agents.rs.rs.bak"];
    for f in &files {
        let path = cli_root.join(f);
        let _ = fs::remove_file(path);
    }
}

/// Normalize path separators: backslash -> forward slash for Cargo.toml compatibility.
fn normalize_path(path: &str) -> String {
    path.replace('\\', "/")
}

/// Validate that all Path sources exist on disk.
pub fn validate_paths(config: &BuildConfig, cli_root: &Path) -> Vec<String> {
    let mut warnings = Vec::new();

    // Check core path
    if let AgentSource::Path { path } = &config.core {
        let full_path = cli_root.join(path);
        if !full_path.join("Cargo.toml").exists() {
            warnings.push(format!(
                "modular-agent-core: path '{path}' does not contain a Cargo.toml"
            ));
        }
    }

    // Check agent paths
    for agent in &config.agents {
        if let AgentSource::Path { path } = &agent.source {
            let full_path = cli_root.join(path);
            if !full_path.join("Cargo.toml").exists() {
                warnings.push(format!(
                    "{}: path '{path}' does not contain a Cargo.toml",
                    agent.name
                ));
            }
        }
    }
    warnings
}
