//! Agent crate imports (auto-generated by ma-build, do not edit)
//!
//! Each `use` pulls in the crate, causing #[modular_agent] registrations
//! to be linked via the `inventory` crate.

#[allow(unused_imports)]
use modular_agent_llm;

#[allow(unused_imports)]
use modular_agent_slack;

#[allow(unused_imports)]
use modular_agent_sqlx;

#[allow(unused_imports)]
use modular_agent_std;

#[allow(unused_imports)]
use modular_agent_web;
